[platformio]
default_envs = hosyond_e32r35t
src_dir = yoRadio/src
data_dir = yoRadio/data

[env:hosyond_e32r35t]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
board_build.filesystem = spiffs
lib_deps =
  adafruit/Adafruit GFX Library@^1.12.1
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
build_flags =
  -D CORE_DEBUG_LEVEL=1
  -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
  -D CONFIG_ASYNC_TCP_USE_WDT=0

